import {useEffect, useRef, useState} from 'react';

const coreLessons=[
 ['🏀','Math','The three-point percentage','Use Warriors-style stats to master ratios and percentages.','A player made 9 of 12 shots. What percent?','75'],
 ['⚽','Science','The science of a Messi pass','Explore forces, motion, and a fair experiment.','What force slows a rolling ball?','friction'],
 ['📖','English','Read like a detective','Find a claim, use evidence, and write a strong paragraph.','Which word gives evidence: because or maybe?','because'],
 ['🧭','Social studies','Who is telling the story?','Compare sources and spot perspective.','A firsthand diary is a ___ source.','primary'],
 ['💵','Money skills','Build your game budget','Balance saving, spending, and a goal with pretend dollars.','You have $30 and save $12. What remains?','18'],
 ['🚀','Entrepreneurship','Your first mini-business','Design a helpful idea and calculate pretend profit.','Revenue minus costs equals what?','profit'],
 ['✦','AI literacy','Coach the computer','Write a clear prompt and check an AI answer.','True or false: AI answers should be checked.','true'],
 ['⌨','Python','Program a scoreboard','Variables, arithmetic, and loops.','Three touchdowns are how many points?','21'],
 ['🧩','Computer science','Think in algorithms','Break a big challenge into clear, testable steps.','An ordered set of steps is an…','algorithm'],
];
const languages={
 english:['English & grammar','Strong sentences','The player passed the ball quickly.','Which word is the adverb?','quickly','Adverbs describe how an action happens.'],
 spanish:['Spanish','¡Hola, Avery!','El equipo juega bien.','What does “equipo” mean?','team','Say it: eh-KEE-poh.'],
 french:['French','Bonjour, Avery !','Nous aimons le football.','What does “nous” mean?','we','The final “s” is usually silent.'],
 mandarin:['Mandarin Chinese','你好, Avery!','我喜欢篮球。 Wǒ xǐhuān lánqiú.','What sport is 篮球 (lánqiú)?','basketball','Practice the tones slowly.'],
 italian:['Italian','Ciao, Avery!','La squadra gioca bene.','What does “squadra” mean?','team','Keep Italian vowels clear.'],
};
const cleanUrl=(text)=>{try{const u=new URL(text);return ['http:','https:'].includes(u.protocol)?u:null}catch{return null}};
const ytId=(text)=>{try{const u=new URL(text);if(u.hostname.includes('youtu.be'))return u.pathname.slice(1);if(u.hostname.includes('youtube.com'))return u.searchParams.get('v')||u.pathname.split('/embed/')[1]}catch{}return null};
const dialogProxy=(id)=>({showModal:()=>document.getElementById(id)?.showModal(),close:()=>document.getElementById(id)?.close()});
const parent=dialogProxy('parent'),help=dialogProxy('help'),willie=dialogProxy('willie');
const photo={set src(value){const el=document.getElementById('photo');if(el)el.src=value},get classList(){return document.getElementById('photo')?.classList}};
function readAloud(text){if(!('speechSynthesis' in window))return alert('Read-aloud is unavailable in this browser.');window.speechSynthesis.cancel();window.speechSynthesis.speak(new SpeechSynthesisUtterance(text))}

function Header({installApp,canInstall}){
 const [music,setMusic]=useState(false);
 const ping=()=>{setMusic(v=>{const next=!v;if(next){const C=window.AudioContext||window.webkitAudioContext;if(C){const c=new C(),o=c.createOscillator(),g=c.createGain();o.frequency.value=196;g.gain.value=.025;o.connect(g).connect(c.destination);o.start();g.gain.exponentialRampToValueAtTime(.001,c.currentTime+1);o.stop(c.currentTime+1)}}return next})};
 return <header><a className="brand" href="#lounge"><img src="/assets/icon.svg" alt=""/><span>AVERY'S<br/><b>CLUBHOUSE</b></span></a><nav aria-label="Main navigation">{[['lounge','Lounge'],['playstation','PS5'],['campus','University'],['languages','Languages'],['guitar','Guitar'],['studio','Creator lab'],['backpack','Backpack']].map(x=><a href={'#'+x[0]} key={x[0]}>{x[1]}</a>)}</nav><div className="utility">{canInstall&&<button onClick={installApp}>＋ <span>Install app</span></button>}<button onClick={()=>document.getElementById('help').showModal()}>🎙 <span>Voice</span></button><button onClick={ping} aria-pressed={music}>♫ <span>{music?'Music on':'Music off'}</span></button></div></header>
}
function Intro({close}){const [muted,setMuted]=useState(true);return <div className="intro" role="dialog" aria-label="Sports intro"><video autoPlay loop muted={muted} playsInline poster="/assets/lounge.png"><source src="/assets/avery-sports-intro.mp4" type="video/mp4"/></video><div className="intro-copy"><small>THE CLUBHOUSE PRESENTS</small><strong>AVERY'S GAME DAY</strong><span>Original fan-made motion graphics</span></div><div className="intro-buttons"><button onClick={()=>setMuted(v=>!v)}>{muted?'🔇 Audio off':'🔊 Audio on'}</button><button className="primary" onClick={close}>Skip intro</button></div></div>}
function TV({close}){
 const [request,setRequest]=useState(''),[src,setSrc]=useState(''),[status,setStatus]=useState('Type a search, paste a link, speak, or upload local media.'),[listening,setListening]=useState(false);const blob=useRef();
 const play=()=>{const q=request.trim().slice(0,300);if(!q)return setStatus('Tell Avery TV what you want to watch.');const id=ytId(q);if(id){setSrc('https://www.youtube-nocookie.com/embed/'+encodeURIComponent(id)+'?autoplay=1');return setStatus('YouTube embed loaded. If playback is blocked, use Open in new tab.')}const u=cleanUrl(q);if(u&&/\.(mp4|webm|ogg|mp3)(\?|$)/i.test(u.pathname)){setSrc(u.href);return setStatus('Direct media loaded.')}if(u)return setStatus('That website may block embedding. Use Open in new tab.');window.open('https://www.youtube.com/results?search_query='+encodeURIComponent(q),'_blank','noopener,noreferrer');setStatus('Search results opened in a new tab. Paste a chosen video URL here.')};
 const speak=()=>{const R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R)return setStatus('Speech input is unsupported here. Type your request instead.');const r=new R();r.lang='en-US';r.onstart=()=>{setListening(true);setStatus('Listening…')};r.onresult=e=>{setRequest(e.results[0][0].transcript);setStatus('Request captured. Select Play / Search.')};r.onerror=e=>setStatus(e.error==='not-allowed'?'Microphone permission was denied. You can still type or paste.':'Speech error: '+e.error);r.onend=()=>setListening(false);r.start()};
 const upload=e=>{const f=e.target.files?.[0];if(!f)return;if(!/^(video|audio)\//.test(f.type))return setStatus('Choose a supported video or audio file.');if(blob.current)URL.revokeObjectURL(blob.current);blob.current=URL.createObjectURL(f);setSrc(blob.current);setStatus(f.name+' is playing locally and was not uploaded.')};
 return <div className="shade" role="dialog" aria-modal="true"><section className="modal"><div className="modal-head"><h2>Avery TV</h2><button onClick={close} aria-label="Close television">×</button></div><div className="tv-screen">{src?(src.includes('youtube-nocookie')?<iframe src={src} title="Avery TV player" allow="autoplay; encrypted-media; picture-in-picture" allowFullScreen/>:<video src={src} controls autoPlay/>):<div><b>AVERY TV</b><span>{status}</span></div>}</div><div className="media-input"><input value={request} onChange={e=>setRequest(e.target.value)} onKeyDown={e=>e.key==='Enter'&&play()} placeholder="Try “Messi skills,” paste a URL, or upload"/><button className={listening?'listening':''} onClick={speak}>{listening?'● Listening':'🎙 Speak'}</button><label className="button">＋ Upload<input type="file" accept="video/*,audio/*" onChange={upload}/></label><button className="primary" onClick={play}>Play / Search</button></div><p role="status" className="status">{status}</p><div className="safe"><button disabled={!request.trim()} onClick={()=>{const u=cleanUrl(request);window.open(u?u.href:'https://www.youtube.com/results?search_query='+encodeURIComponent(request),'_blank','noopener,noreferrer')}}>Open in new tab ↗</button><span>No arbitrary URL proxying. Outside sites control whether embeds work.</span></div></section></div>
}
function Lounge(){const [tv,setTv]=useState(false);return <main id="lounge"><p className="eyebrow">YOUR SPACE · GAME, CREATE, LEVEL UP</p><div className="title-row"><h1>Welcome home, Avery.</h1><span className="pill">49ers · Warriors · Messi</span></div><div className="hero"><img src="/assets/lounge.png" alt="Photorealistic sports lounge with a large television, guitar, football and basketball collectibles"/><button className="power" onClick={()=>setTv(true)}><b>▶</b><strong>AVERY TV</strong><small>Speak, search, paste, or upload</small></button><span className="hero-label">THE 49ERS LOUNGE · FAN-MADE SPACE</span></div><div className="quick">{['🏈 49ers','🏀 Warriors','⚽ Messi'].map(x=><button key={x} onClick={()=>setTv(true)}>{x}</button>)}<a className="button" href="#guitar">🎸 Guitar</a><button onClick={()=>{sessionStorage.removeItem('skipIntro');location.reload()}}>▶ Clubhouse intro</button><a href="#campus">Today's learning quest →</a></div><p className="note">External results are not age-filtered. Use a parent-supervised account and review media together.</p>{tv&&<TV close={()=>setTv(false)}/>}</main>}
function PS5(){return <main id="playstation"><p className="eyebrow">PLAYER TWO? YOU'RE PLAYER ONE.</p><h1>Your PS5 station.</h1><div className="cols2"><section className="ps"><b>PS5</b><h2>Digital Edition</h2><p>Your games live in your PlayStation library. No disc drive needed.</p><a className="button primary" href="https://store.playstation.com/" target="_blank" rel="noreferrer">Open PlayStation Store ↗</a><small>Ask a parent before downloading or purchasing.</small></section><section className="card"><h2>Play your console on a computer</h2><ol><li>With a parent, install Sony's PS Remote Play app.</li><li>Enable Remote Play in PS5 Settings → System.</li><li>Use the appropriate PlayStation account.</li><li>Connect a supported controller.</li></ol><a className="button" href="https://www.playstation.com/en-us/remote-play/" target="_blank" rel="noreferrer">Get official Remote Play ↗</a><p className="note">Requires Sony's app and configured console. This site cannot stream a PS5 directly.</p></section></div></main>}
function Quest({lesson,close}){const [answer,setAnswer]=useState(''),[feedback,setFeedback]=useState('');return <div className="shade" role="dialog" aria-modal="true"><section className="modal lesson"><div className="modal-head"><h2>{lesson[2]}</h2><button onClick={close}>×</button></div><p>{lesson[4]}</p><input value={answer} onChange={e=>setAnswer(e.target.value)} placeholder="Your answer"/><button className="primary" onClick={()=>setFeedback(answer.toLowerCase().includes(lesson[5])?'Nice work — correct!':'Good try. Re-read the clue and try again.')}>Check answer</button><p role="status">{feedback}</p></section></div>}
function Campus(){const [q,setQ]=useState(''),[active,setActive]=useState();return <main id="campus"><p className="eyebrow">AVERY UNIVERSITY · GRADE 7</p><div className="title-row"><h1>Small quests. Big skills.</h1><a className="button" href="#languages">Language lab</a></div><label>Find a subject<input type="search" value={q} onChange={e=>setQ(e.target.value)} placeholder="Try money, Python, science…"/></label><div className="grid">{coreLessons.filter(x=>x.join(' ').toLowerCase().includes(q.toLowerCase())).map((x,i)=><article className="lesson-card" key={x[2]}><span>{x[0]}</span><small>{x[1].toUpperCase()} · {6+i%3} MIN</small><h2>{x[2]}</h2><p>{x[3]}</p><button onClick={()=>setActive(x)}>Start quest →</button></article>)}</div><p className="note">Local starter lessons for Grade 7 practice; not a replacement for school curriculum.</p>{active&&<Quest lesson={active} close={()=>setActive()}/>}</main>}
function Languages(){const [lang,setLang]=useState('english'),[level,setLevel]=useState(1),[answer,setAnswer]=useState(''),[feedback,setFeedback]=useState(''),[progress,setProgress]=useState(20);const l=languages[lang];return <main id="languages"><p className="eyebrow">LANGUAGE LAB · LOCAL LESSON MODE</p><h1>Say it. Shape it. Own it.</h1><div className="tabs" role="tablist">{Object.entries(languages).map(([k,v])=><button role="tab" aria-selected={k===lang} onClick={()=>{setLang(k);setAnswer('');setFeedback('')}} key={k}>{v[0]}</button>)}</div><section className="language-card"><div><small>LEVEL {level} OF 3 · {progress}% COMPLETE</small><h2>{l[1]}</h2><p className="phrase">{l[2]}</p><button onClick={()=>readAloud(l.slice(1,4).join('. '))}>▶ Read aloud</button></div><div><label>Difficulty<select value={level} onChange={e=>setLevel(e.target.value)}><option value="1">Warm-up</option><option value="2">Practice</option><option value="3">Challenge</option></select></label><p><b>{l[3]}</b></p><input value={answer} onChange={e=>setAnswer(e.target.value)} placeholder="Type your answer"/><button className="primary" onClick={()=>{const ok=answer.toLowerCase().includes(l[4]);setFeedback(ok?'Correct! '+l[5]:'Almost. Hint: '+l[5]);if(ok)setProgress(p=>Math.min(100,p+20))}}>Check answer</button><p role="status">{feedback}</p><div className="progress"><i style={{width:progress+'%'}}/></div></div></section><div className="provider"><b>Tutor status: Local lesson mode</b><span>No AI provider is configured. Feedback uses included demo content.</span></div></main>}
function Guitar(){const [tempo,setTempo]=useState(80),[seconds,setSeconds]=useState(600),[running,setRunning]=useState(false);const timer=useRef();useEffect(()=>()=>clearInterval(timer.current),[]);const tone=f=>{const C=window.AudioContext||window.webkitAudioContext;if(!C)return alert('Audio unavailable.');const c=new C(),o=c.createOscillator(),g=c.createGain();o.frequency.value=f;g.gain.value=.06;o.connect(g).connect(c.destination);o.start();g.gain.exponentialRampToValueAtTime(.001,c.currentTime+1);o.stop(c.currentTime+1)};return <main id="guitar"><p className="eyebrow">THE GUITAR STUDIO</p><h1>Make a little noise.</h1><div className="cols3"><section className="card"><b className="num">01</b><h2>Tune up</h2><p>Tap a reference tone, then compare your string.</p><div className="strings">{[['E',82],['A',110],['D',147],['G',196],['B',247],['e',330]].map(x=><button onClick={()=>tone(x[1])} key={x[0]}>{x[0]}</button>)}</div></section><section className="card"><b className="num">02</b><h2>First four chords</h2><p>Try Em, G, C, and D. Keep fingertips curved.</p><a className="button" href="https://www.youtube.com/results?search_query=beginner+guitar+chords+lesson" target="_blank" rel="noreferrer">Find a video lesson ↗</a></section><section className="card"><b className="num">03</b><h2>Find your rhythm</h2><p>Count 1, 2, 3, 4 and strum each beat.</p><label>Tempo<input type="range" min="50" max="160" value={tempo} onChange={e=>setTempo(e.target.value)}/></label><b>{tempo} BPM</b></section></div><div className="practice"><b>{String(Math.floor(seconds/60)).padStart(2,'0')}:{String(seconds%60).padStart(2,'0')}</b><span>Ten focused minutes.</span><button onClick={()=>{if(running){clearInterval(timer.current);setRunning(false)}else{setRunning(true);timer.current=setInterval(()=>setSeconds(s=>Math.max(0,s-1)),1000)}}}>{running?'Pause practice':'Start practice'}</button><button onClick={()=>{clearInterval(timer.current);setRunning(false);setSeconds(600)}}>Reset</button><label><input type="checkbox"/> I practiced today</label></div></main>}
function Studio(){const [tab,setTab]=useState('python'),[code,setCode]=useState('name = "Avery"\ntouchdowns = 3\npoints = touchdowns * 7\nprint(name, "scored", points, "points!")'),[out,setOut]=useState('Your output will appear here.'),[badge,setBadge]=useState("Avery's First Touchdown");return <main id="studio"><p className="eyebrow">BUILD SOMETHING THAT'S YOURS</p><h1>The creator lab.</h1><div className="tabs">{[['python','Python playground'],['badge','Digital badge'],['photo','Photo animation'],['remotion','Remotion studio']].map(x=><button aria-selected={tab===x[0]} onClick={()=>setTab(x[0])} key={x[0]}>{x[1]}</button>)}</div><section className="card lab">{tab==='python'&&<><h2>Code a scoreboard</h2><textarea value={code} onChange={e=>setCode(e.target.value)} aria-label="Python code"/><button className="primary" onClick={()=>setOut('Avery scored '+Number(code.match(/touchdowns\s*=\s*(\d+)/)?.[1]||3)*7+' points!')}>▶ Run lesson</button><pre>{out}</pre><small>Demo arithmetic evaluator; it does not execute arbitrary code.</small></>}{tab==='badge'&&<><h2>Your first collectible — without crypto money</h2><p>Practice metadata only. Not minted, for sale, or financially valuable.</p><label>Badge name<input value={badge} onChange={e=>setBadge(e.target.value)}/></label><button onClick={()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify({name:badge,kind:'practice-badge'},null,2)],{type:'application/json'}));a.download='avery-practice-badge.json';a.click()}}>Export metadata JSON</button><div className="badge">★<h3>{badge}</h3><span>Python rookie</span></div></>}{tab==='photo'&&<><h2>Make a photo move</h2><p>2D keyframe practice. Local files never leave this browser.</p><label className="button">Choose a photo<input type="file" accept="image/*" onChange={e=>{const f=e.target.files?.[0];if(f)photo.src=URL.createObjectURL(f)}}/></label><img id="photo" className="photo" src="/assets/willie-avatar.webp" alt="Animation exercise preview"/><button onClick={()=>photo.classList.toggle('moving')}>Play / pause keyframes</button></>}{tab==='remotion'&&<><h2>Your game-day intro</h2><p>Editable Remotion composition with original fan motion graphics — no broadcast footage or endorsement claim.</p><video className="preview" controls loop poster="/assets/lounge.png"><source src="/assets/avery-sports-intro.mp4" type="video/mp4"/></video><a className="button" href="/remotion-source.txt" download>Download composition guide</a><span className="pill">Rendered locally · original media</span></>}</section></main>}
function Backpack(){const [url,setUrl]=useState(''),[links,setLinks]=useState([]),[notes,setNotes]=useState('');const download=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([notes],{type:'text/plain'}));a.download='avery-notes.txt';a.click()};return <main id="backpack"><p className="eyebrow">IDEAS, HOMEWORK, CREATIONS</p><h1>Your session backpack.</h1><p>Files stay in this tab and disappear when it closes.</p><label className="button">＋ Choose files<input type="file" multiple onChange={e=>alert(e.target.files.length+' local file(s) ready for this session.')}/></label><div className="link-form"><input value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://… add a website link"/><button onClick={()=>{const u=cleanUrl(url);if(!u)return alert('Enter a complete http or https link.');setLinks(v=>[...v,u.href]);setUrl('')}}>Add link</button></div>{links.map(x=><p key={x}><a href={x} target="_blank" rel="noreferrer">{x} ↗</a></p>)}<h2>Your working notes</h2><textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Write notes here. Avoid addresses, passwords, and personal information."/><div className="actions"><button onClick={()=>readAloud(notes)}>▶ Read notes</button><button onClick={download}>Download notes</button><button onClick={()=>window.print()}>Print notes</button><button disabled={!navigator.share} title={!navigator.share?'Sharing is unsupported in this browser':''} onClick={()=>navigator.share({title:"Avery's notes",text:notes})}>Share…</button></div></main>}
function Footer(){return <><footer><span>Avery's Clubhouse · Fan-made, not affiliated with any team or platform.</span><button onClick={()=>parent.showModal()}>Parent corner</button><button onClick={()=>help.showModal()}>Voice commands & help</button></footer><a className="home" href="#lounge" aria-label="Return to lounge">⌂</a><button className="willie" onClick={()=>willie.showModal()}><img src="/assets/willie-avatar.webp" alt=""/>Ask Willie</button><dialog id="parent"><button className="close" onClick={()=>parent.close()}>×</button><h2>Parent corner</h2><p>This is public guidance, not a password-protected child lock. Avery's Clubhouse requires no login.</p><h3>Learning and account safety</h3><p>The tutor uses included local lessons, not a connected language model. External media is not age-filtered.</p><h3>Privacy</h3><p>Uploads stay in the session. Voice recognition and embeds may contact their providers.</p></dialog><dialog id="help"><button className="close" onClick={()=>help.close()}>×</button><h2>Voice & accessibility help</h2><p>Open Avery TV and select Speak. If speech recognition is unavailable, type the same request.</p><p>Use Tab to reach controls, Enter to activate, and Escape to close dialogs.</p></dialog><dialog id="willie"><button className="close" onClick={()=>willie.close()}>×</button><h2>Ask Willie</h2><p><b>Local tutor mode:</b> I can guide you through the included lessons. Live AI requires provider configuration.</p><a className="button" href="#languages" onClick={()=>willie.close()}>Open language lab</a></dialog></>}
export function App(){const [intro,setIntro]=useState(()=>!new URLSearchParams(location.search).has('skipIntro')&&sessionStorage.getItem('skipIntro')!=='yes'),[installPrompt,setInstallPrompt]=useState(null);useEffect(()=>{const ready=e=>{e.preventDefault();setInstallPrompt(e)};window.addEventListener('beforeinstallprompt',ready);return()=>window.removeEventListener('beforeinstallprompt',ready)},[]);const close=()=>{sessionStorage.setItem('skipIntro','yes');setIntro(false)};const installApp=async()=>{if(!installPrompt)return;await installPrompt.prompt();await installPrompt.userChoice;setInstallPrompt(null)};return <>{intro&&<Intro close={close}/>}<Header installApp={installApp} canInstall={!!installPrompt}/><Lounge/><PS5/><Campus/><Languages/><Guitar/><Studio/><Backpack/><Footer/></>}
